export const TABS = Object.freeze({
  KEYWORD: 'KEYWORD',
  OVERALL_LOCAL_CONGESTION: 'OVERALL_LOCAL_CONGESTION',
  PARTIAL_LOCAL_CONGESTION: 'PARTIAL_LOCAL_CONGESTION',
  TRAFFIC_CONDITIONS: 'TRAFFIC_CONDITIONS',
  SUBWAY_CONDITIONS: 'SUBWAY_CONDITIONS',
});
